INSERT INTO USUARIO (NM_LOGIN, DS_SENHA, NM_USUARIO_CRIACAO, DH_CRIACAO) 
VALUES ('admin', '$2a$10$RfP9tkO1.23cXAzYqU4WDOx2w1z5RK6mfErXnpJ07SuzHql/Mgc4q', 'Sistema', CURRENT_TIMESTAMP);

INSERT INTO ARTISTA (NM_NOME, NM_USUARIO_CRIACAO, DH_CRIACAO) VALUES
('Legião Urbana', 'admin', CURRENT_TIMESTAMP),
('Paralamas do Sucesso', 'admin', CURRENT_TIMESTAMP),
('Titãs', 'admin', CURRENT_TIMESTAMP),
('Sepultura', 'admin', CURRENT_TIMESTAMP),
('Chico Buarque', 'admin', CURRENT_TIMESTAMP);
