CREATE TABLE ARTAISTA (
    ID BIGSERIAL PRIMARY KEY,
    NM_NOME VARCHAR(255) NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP
);

CREATE TABLE ALBUM (
    ID BIGSERIAL PRIMARY KEY,
    NM_TITULO VARCHAR(255) NOT NULL,
    ART_ID BIGINT NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP
    CONSTRAINT FK_ALBUM_ARTISTA
        FOREIGN KEY (ART_ID)
        REFERENCES ARTAISTA (ID)
);

CREATE TABLE ALBUM_IMAGEM (
    ID BIGSERIAL PRIMARY KEY,
    ALB_ID BIGINT NOT NULL,
    NM_IMAGEM VARCHAR(255) NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP
    CONSTRAINT FK_ALBUM_IMAGEM_ALBUM
        FOREIGN KEY (ALB_ID)
        REFERENCES ALB_ALBUM (ID)
);