CREATE TABLE ARTISTA (
    ID BIGSERIAL PRIMARY KEY,
    NM_NOME VARCHAR(255) NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP
);

CREATE TABLE ALBUM (
    ID BIGSERIAL PRIMARY KEY,
    NM_TITULO VARCHAR(255) NOT NULL,
    ART_ID BIGINT NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_ALBUM_ARTISTA
        FOREIGN KEY (ART_ID)
        REFERENCES ARTISTA (ID)
);

CREATE TABLE ALBUM_IMAGEM (
    ID BIGSERIAL PRIMARY KEY,
    ALB_ID BIGINT NOT NULL,
    NM_IMAGEM VARCHAR(255) NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255) NOT NULL,
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_ALBUM_IMAGEM_ALBUM
        FOREIGN KEY (ALB_ID)
        REFERENCES ALBUM (ID)
);

CREATE TABLE USUARIO (
    ID BIGSERIAL PRIMARY KEY,
    NM_LOGIN VARCHAR(100) UNIQUE NOT NULL,
    DS_SENHA VARCHAR(255) NOT NULL,
    NM_USUARIO_CRIACAO VARCHAR(255),
    NM_USUARIO_ATUALIZACAO VARCHAR(255),
    DH_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DH_ATUALIZACAO TIMESTAMP
);